module.exports = {
  localAuth: 'localAuth',
  token: 'token',
  users: 'users',
  cosHelper: 'cosHelper',
  cosHelperType: 'cosHelperType',
  representWork: 'representWork',
  vote: 'cosHelperVote',
  comments: 'comments',
  commentsActive: 'commentsActive',
  commentWeight: 'commentWeight',
  imMember: 'imMember',
  imRoom: 'imRoom',
  imContent: 'imContent',
  feedback: 'feedback',
};
